### ISSUE TITLE
Ränder gehen nicht bis zum Ende durch 

### ISSUE THREAD

**Issue by johan-t** [johan-t/Memoriter#17]
Die blauen Ränder gehen nicht bis zum Ende durch. Eigentlich sollten sie bis zum Ende der Seite sich durchziehen, enden aber schon vor dem Footer seperator.
Dies liegt glaube ich daran, dass der Footer unter den Linien gerendert wird und diese deshalb nie tiefer als der der footer gehen können

**Comment by q-Sci** [comment]
outdated
