### ISSUE TITLE
Text der Karteikarte ist noch nicht optimal

### ISSUE THREAD

**Issue by johan-t** [johan-t/Memoriter#18]
Bei der Topic Page ist der Text der einzelnen Karteikarte noch nicht optimal formatiert. Obwohl es optisch okay aussieht muss das CSS eigentlich angepasst werden, dass der Text von alleine manipuliert wird und in den Rahmen der Karteikarte passt. Dies geschieht bis jetzt noch nicht sondern ich habe die CSS Properties des Textes formatiert

**Comment by q-Sci** [comment]
outdated
